#!user/bin/python
class Elipse:
	def __init__(self, a,b):
		self.a = a
		self.b = b
	def area(self):
		print ( self.a * self.b * 3.14 / 4 )  
	def perimeter(self):
		print ( self.a * self.b * 3.14 / 4 )
	def point(self,x,y):
		#eqspresion for point
a = input("a = ")
b = input("b = ")
triangle = Triangle(a,b)
x = input("x= ")
y = input("y= ")
triangle.point(x,y)
triangle.area()
triangle.perimeter()
