#!user/bin/python
class Triangle:
	def __init__(self, x1,y1,x2,y2,x3,y3):
		self.x1 = x1
		self.y1 = y1
		self.x2 = x2
		self.y2 = y2
		self.x3 = x3
		self.y3 = y3
	def area(self):
		#eqspression for area
	def perimeter(self):
		#eqspression for perimeter
	def point(self,x,y):
		#eqspresion for oint
x1 = input("x1 = ")
y1 = input("y1 = ")
x2 = input("x2 = ")
y2 = input("y2 = ")
x3 = input("x3 = ")
y3 = input("y3 = ")
triangle = Triangle(x1,y1,x2,y2,x3,y3)
x = input("x= ")
y = input("y= ")
triangle.point(x,y)
triangle.area()
triangle.perimeter()

	
