/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Math */

#ifndef _Included_Math
#define _Included_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Math
 * Method:    getFactorial
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Math_getFactorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     Math
 * Method:    getMax
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_Math_getMax
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     Math
 * Method:    getMin
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_Math_getMin
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     Math
 * Method:    sortArrToMax
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_Math_sortArrToMax
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     Math
 * Method:    sortArrToMin
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_Math_sortArrToMin
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
