/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyMath */

#ifndef _Included_MyMath
#define _Included_MyMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyMath
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MyMath_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     MyMath
 * Method:    getMax
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_MyMath_getMax
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyMath
 * Method:    getMin
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_MyMath_getMin
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyMath
 * Method:    sortArrToMax
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_MyMath_sortArrToMax
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyMath
 * Method:    sortArrToMin
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_MyMath_sortArrToMin
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
