/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class File */

#ifndef _Included_File
#define _Included_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     File
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_File_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     File
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_File_read
  (JNIEnv *, jobject);

/*
 * Class:     File
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_File_create
  (JNIEnv *, jobject);

/*
 * Class:     File
 * Method:    delete
 * Signature: ()V
 */
/*JNIEXPORT void JNICALL Java_File_delete
  (JNIEnv *, jobject);*/

/*
 * Class:     File
 * Method:    createFileWithPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_File_createFileWithPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     File
 * Method:    deleteFileWithPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_File_deleteFileWithPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
