/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Math */

#ifndef _Included_Math
#define _Included_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Math
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Math_factorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     Math
 * Method:    max
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Math_max
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Math
 * Method:    min
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Math_min
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Math
 * Method:    referanceSort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Math_referanceSort
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Math
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Math_sort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
