/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class File */

#ifndef _Included_File
#define _Included_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     File
 * Method:    rwFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_File_rwFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
