/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFile */

#ifndef _Included_JNIFile
#define _Included_JNIFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFile
 * Method:    fileActions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIFile_fileActions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
