/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCallsClass */

#ifndef _Included_NativeCallsClass
#define _Included_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCallsClass
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeCallsClass_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeCallsClass
 * Method:    sortArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_NativeCallsClass_sortArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     NativeCallsClass
 * Method:    returnSortArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_NativeCallsClass_returnSortArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     NativeCallsClass
 * Method:    max
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_NativeCallsClass_max
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     NativeCallsClass
 * Method:    min
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_NativeCallsClass_min
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
