/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeClass */

#ifndef _Included_NativeClass
#define _Included_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeClass
 * Method:    WorkToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeClass_WorkToFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
