/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeClass */

#ifndef _Included_NativeClass
#define _Included_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeClass
 * Method:    FileClass
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeClass_FileClass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeClass
 * Method:    Create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeClass_Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeClass
 * Method:    Write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeClass_Write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeClass
 * Method:    Read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeClass_Read
  (JNIEnv *, jobject);

/*
 * Class:     NativeClass
 * Method:    Delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeClass_Delete
  (JNIEnv *, jobject);

/*
 * Class:     NativeClass
 * Method:    CreateStatic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeClass_CreateStatic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NativeClass
 * Method:    DeleteStatic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeClass_DeleteStatic
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
