/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyFunctions */

#ifndef _Included_MyFunctions
#define _Included_MyFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyFunctions
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MyFunctions_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     MyFunctions
 * Method:    min
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_MyFunctions_min
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyFunctions
 * Method:    max
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_MyFunctions_max
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyFunctions
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_MyFunctions_sort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyFunctions
 * Method:    sortReferance
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_MyFunctions_sortReferance
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
