/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIMath */

#ifndef _Included_JNIMath
#define _Included_JNIMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIMath
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIMath_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIMath
 * Method:    maxElement
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JNIMath_maxElement
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JNIMath
 * Method:    minElement
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JNIMath_minElement
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JNIMath
 * Method:    sortArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_JNIMath_sortArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JNIMath
 * Method:    sortArrayVoid
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_JNIMath_sortArrayVoid
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
